### ISSUE TITLE
Structure of ``books`` is not mirrored in docs

### ISSUE THREAD

**Issue by Clonkk** [SciNim/getting-started#12]
Having nested folder in books do not result in an arborescence in ``docs`` see the buld in my fork : https://github.com/Clonkk/getting-started/runs/2583163378?check_suite_focus=true

**Comment by HugoGranstrom** [comment]
Hmm it seems like it's the fact that the folder structure doesn't exists that it fails. I tried and `writeFile` which Nimib uses internally can't create folders, they must already exist.

**Comment by Clonkk** [comment]
We could solve this in the nimble task using mkDir

**Comment by pietroppeter** [comment]
> Hmm it seems like it's the fact that the folder structure doesn't exists that it fails. I tried and `writeFile` which Nimib uses internally can't create folders, they must already exist.
> 
> And I guess it hasn't been a problem for Nimib prior to this because the HTML was always placed besides the nim file so the folders was guaranteed to already exist. Feels like an Nimib issue

another point to be fixed also in nimib. this is really helpful. I will open a meta issue in nimib to track all these discussions.

> We could solve this in the nimble task using mkDir

feel free to add a temportary fix, but if you also want to try a PR* in nimib... 😄 

*the idea as @HugoGranstrom noted would be to use an improved `writeFile`...

**Comment by HugoGranstrom** [comment]
It should just be a matter of adding a `splitFile` and a `createDir` to make it work. I can fix a PR for Nimib if Clonkk doesn't beat me to it

**Comment by HugoGranstrom** [comment]
PR submitted to Nimib: https://github.com/pietroppeter/nimib/pull/44 that should solve this issue

**Comment by pietroppeter** [comment]
release a 0.1.1 with the fix merged: https://github.com/pietroppeter/nimib/releases/tag/v0.1.1
