### ISSUE TITLE
features need in nimibook to start using it?

### ISSUE THREAD

**Issue by pietroppeter** [SciNim/getting-started#13]
given current progress in https://github.com/pietroppeter/nimibook I think we can start to ask ourselves when this project can migrate to use nimibook. Which feature do we still want from nimibook that we want to use here?

Later we will also need to manage how to update this repo when nimib and nimibook evolve, but I guess this is a separate issue and we will tackle it when we have it, but if we already start with a good set of feature this other problem is postponed.

As far as I can see I would at least add the [markdown support in nimibook](https://github.com/pietroppeter/nimibook/issues/8), which seems reasonably easy to do and possibly useful for pages without nim code.

**Comment by HugoGranstrom** [comment]
As far as I'm concerned looking at https://pietroppeter.github.io/nimibook/ I don't see that many features specific to Nimibook that should stop from getting started using it. Once it's able to generate the TOC and build everything by itself I see no reason to wait any longer. (With Clonkk's PR we are basically there?)

Updating shouldn't be much of a problem as most of the Nimibook code is in `src/` and if we don't touch it it's just a matter of copy-pasting it. 

Yes `.md`-support would be nice to have. And that reminds me that I should look at the possibility of a VS Code plugin for highlighting the markdown in `nbText` blocks.

**Comment by HugoGranstrom** [comment]
Markdown support has been added and a plan for how to update it in the future has been established (nimibook as a package which modifies files in the repo). Are we ready to move over to using nimiBook @Clonkk ?

**Comment by Clonkk** [comment]
I think with #19 merged we're good to go !

**Comment by HugoGranstrom** [comment]
@Clonkk it's not more than fair that you get to be the one to `init` this after all the work you've put into it 😄

**Comment by Clonkk** [comment]
I was already on it
