### ISSUE TITLE
Improve github-pages

### ISSUE THREAD

**Issue by Clonkk** [SciNim/getting-started#7]
To have a pretty tutorial we'd need the following features : 
* [x] Generating the index.html file (it's the landing page of github pages, litterally the first thing we see) 
* [x] Having a table of content on each page to quickly navigate between pages
* [x] CSS theme to make it look pretty

**Comment by HugoGranstrom** [comment]
Regarding the CSS, the main drawback of the default theme IMO is that it doesn't separate code and text clearly, so adding a different background to the code might be a good idea.

**Comment by pietroppeter** [comment]
> Regarding the CSS, the main drawback of the default theme IMO is that it doesn't separate code and text clearly, so adding a different background to the code might be a good idea.

this I would say it is also a bug of nimib. originally water.css had a better background for code. when picking androidstudio for highlighting, this replaces the code background with a lighter one (you can easily verify this inspecting the page). I will have to make sure that default code background stays the one of water.css.

**Comment by HugoGranstrom** [comment]
I see, disabling it in the devtools does make it look better 🚀 Something I noticed when inspecting the CSS was that the output blocks didn't have any background color at all. I want to remember that last time I tried Nimib out it did have a background as well, but I may also misremeber 🤔

**Comment by pietroppeter** [comment]
no the output never had a background (in water.css). regarding the default styling of nimib it can certainly be improved and it will be improved (and a more visible output block is something I agree on also).

With respect to current default, I wanted to start with something that was minimal and would work out of the box. After trying out many of the no-class minimal css frameworks (here is [nice page](https://dohliam.github.io/dropin-minimal-css/) that collects many of them in a demo way), [water.css](https://watercss.kognise.dev/) was the only one that required absolutely no tweaking and would look good enough. I would definitely encourage us to tweak the css here and then next default might be able to incorporate some of the improvements that was done here or elsewhere.

**Comment by HugoGranstrom** [comment]
Okay, bad memory than :) Nice, and it doesn't seem to hard to do either, add a class and of we go. 

Totally understandable, and it looks great in every other regard. I tested a few random ones on the page you linked and Water was the nicest of them all. 
Sounds like a plan! Is `nbDoc.context["stylesheet"]` the only way to modify styles at the moment? Ie to override one aspect of Water.css for example I will copy it and modify it?

**Comment by pietroppeter** [comment]
if you want to ovveride a single element of style I would add a `head_other.mustache` template with the content you need.
I use this mechanism for all of my nimib projects to add [plausible analytics](https://plausible.io/simple-web-analytics) (a very nice, open and privacy friendly alternative to google analytics). Actually on that subject if you want to add analytics to this project too, I can make it available through my account, plausible allows to make the analytics dahsboard public (see for example https://plausible.io/pietroppeter.github.io%2Fnimib) and I have a lot of views unused! :D

**Comment by HugoGranstrom** [comment]
> if you want to ovveride a single element of style I would add a head_other.mustache template with the content you need.

Oh that seems like exactly what I'm looking for, thanks 😃 I see the partial called `left` as well in the body. I guess that would be the place to put our Table of Content. Would it be sensible for us to generate a `TOC.mustache` when doing `nimble genbook` and just having it included in every page? But we may have to loop over all files twice because every file needs `TOC.mustache` when compiling, right? I feel like I'm bombarding you with questions now 😅

> Actually on that subject if you want to add analytics to this project too, I can make it available through my account, plausible allows to make the analytics dahsboard public (see for example plausible.io/pietroppeter.github.io%2Fnimib) and I have a lot of views unused! :D

If you would like to I'm sure everyone would be very grateful! :D And of course if you in the future for whatever reason need to cancel your Plausible subscription just tell us and we'll switch it out 😄 I'm having something similar for my personal site called [GoatClicker](https://www.goatcounter.com/) which also should be privacy and GDPR friendly, plus they have a free plan for non-commercials. But they don't seem to have public dashboards so that's definitely a plus for Plausible. Once again, we would be very thankful for your generosity. :D

**Comment by pietroppeter** [comment]
> Would it be sensible for us to generate a TOC.mustache when doing nimble genbook and just having it included in every page? But we may have to loop over all files twice because every file needs TOC.mustache when compiling, right?

yes, that is a good option. you could generate a toc.mustache first and then when you generate the pages every page will take the generated toc.mustache, so probably you would not need to have a double pass over files (but there might be gotchas there).

**Comment by HugoGranstrom** [comment]
I'll try it out then :) Not that it matters but by two passes I meant that to create toc.mustache we have to pass through all the files once, and then we have to pass over all files again to generate the pages but as I said it doesn't matter. As long as it works, it work ;)

**Comment by HugoGranstrom** [comment]
I guess the next step when we get the general layout fixed is to make the TOC reflect the folder structure so that files in the same folder are clumped together.

**Comment by Clonkk** [comment]
All of these are implemented in the current Nimibook
